### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by fb-sean** [erickmack/streamUpdaterBot#2]
I dont know but i think thats a old methode for that but the OAuth give me everytime a error for no permissions? (RAW CODE)

I only Changed the .env

Error: https://cloe.bhop.xyz/sLigbAk1tKm // Screenshot hoster

My .env:

CREATOR_ID=340243638892101646 // My DC ID
BOT_TOKEN=*** // Bot Token
CLIENT_ID=*** // Client ID
SECRET_TOKEN=***  // Secret Token
DB_URI=mongodb://localhost:***/*** // My URI
PREFIX=!

**Comment by ErickOhm** [comment]
You seem to be getting an unauthorized error from the twitch API, are you sure you have access to it? you must make a POST request to 
```https://id.twitch.tv/oauth2/token?client_id=<CLIENT_ID>&client_secret=<CLIENT_SECRET>&grant_type=client_credentials```
with your credentials and you'll get the token that goes in SECRET_TOKEN, I tested and it still works.

**Comment by fb-sean** [comment]
Oh I check it tomorrow when I am on my pc.

**Comment by fb-sean** [comment]
Thanks for the help now it works.
